Update flask-restx to version 0.5.1
AnacondaRecipes/flask-restx-feedstock pull request #2
Opened 2021-10-20 20:43 UTC by varlackc

1. check the upstream
https://github.com/python-restx/flask-restx/tree/0.5.1

2. check the pinnings
https://github.com/python-restx/flask-restx/blob/0.5.1/tox.ini
https://github.com/python-restx/flask-restx/blob/0.5.1/tasks.py
https://github.com/python-restx/flask-restx/blob/0.5.1/setup.py
https://github.com/python-restx/flask-restx/blob/0.5.1/setup.cfg

3. check changelogs
https://github.com/python-restx/flask-restx/blob/0.5.1/CHANGELOG.rst

all of the changes mentioned are bug fixes

- Fix Marshaled nested wildcard field with ordered=True (#326) [bdscharf]
- Fix Float Field Handling of None (#327) [bdscharf, TVLIgnacy]
- Fix Werkzeug and Flask > 2.0 issues (#341) [hbusul]
- Hotfix package.json [xuhdev]

4. additional research
https://github.com/conda-forge/flask-restx-feedstock/issues

5. verify dev_url
6. verify doc_url
7. added pip to the test section
8. verify the test section
9. additional tests

In order to test the `flask-restx` package version `0.5.1` the following command was used:
`conda build flask-feedstock --test` 
The test result was the following:
`All tests passed`

In addition the `tranquilizer` package was used to test the `flask-restx` package.
The pinning for `flask-restx` in the `tranquilizer` package was modified to use `0.5.1`
The following command was used:
`conda build tranquilizer-feedstock --test`
The test result was the following:
`All tests passed`

Based on the research findings and on the test results we can conclude that it is safe to update `flask-restx` to version `0.5.1`

2021-10-21 14:27 UTC, skupr-anaconda commented
1. werkzeug !=2.0.0 https://github.com/python-restx/flask-restx/blob/88497ced96674916403fa7829de693eaa3485a08/requirements/install.pip#L5
2. 
- Missing wheel package in requirements
- Missing setuptools package in requirements

2021-10-21 20:39 UTC, varlackc commented
> 1. werkzeug !=2.0.0 https://github.com/python-restx/flask-restx/blob/88497ced96674916403fa7829de693eaa3485a08/requirements/install.pip#L5
> 
> * Missing wheel package in requirements
> * Missing setuptools package in requirements

`Wheel` and `setuptools` were added to the meta.yaml file
https://github.com/AnacondaRecipes/flask-restx-feedstock/blob/update_to_0.5.1/recipe/meta.yaml#L22&L23

2021-10-22 09:34 UTC, katietz reviewed
Thanks

2021-10-22 09:34 UTC, katietz commented on recipe/meta.yaml
>      - flask >=0.8,<2.0.0
is it werkzeus <2.0.0.  From what I understood it is !=2.0.0

2021-10-22 09:36 UTC, katietz commented on recipe/meta.yaml
>      - flask >=0.8,<2.0.0
also flask seems to be >=0.8, !=2.0.0.  Not necessarily disallowing anything above 2.0.0

2021-10-28 04:49 UTC, varlackc commented on recipe/meta.yaml
>      - pytz
Corrected the pinnings for flask and werkzeug accourding to the following link
https://github.com/python-restx/flask-restx/blob/88497ced96674916403fa7829de693eaa3485a08/requirements/install.pip#L4&L5

The changes made are included in the following link:
https://github.com/AnacondaRecipes/flask-restx-feedstock/blob/update_to_0.5.1/recipe/meta.yaml#L28&L29

2021-10-28 04:52 UTC, varlackc commented on recipe/meta.yaml
>      - flask >=0.8,<2.0.0
The pinnings have been updated per the following dependency specifications:
https://github.com/python-restx/flask-restx/blob/88497ced96674916403fa7829de693eaa3485a08/requirements/install.pip#L4&L5

2021-10-28 06:43 UTC, skupr-anaconda approved these changes

2021-10-28 12:20 UTC, katietz requested changes
As this package has a runtime dependecy of python >3.6, so I suggest that you add a skip for python <36

2021-10-28 15:04 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True  # [py36]
Should be `skip: True  # [py<36]`

2021-10-29 07:10 UTC, katietz approved these changes
Thanks

2021-11-02 13:55 UTC, merged